### ISSUE TITLE
Question about Parsing Dataset in `generate_dataset.py`

### ISSUE THREAD

**Issue by Sparrow612** [SPFresh/SPFresh#1]
Guys, I think the [generate_dataset.py](https://github.com/SPFresh/SPFresh/blob/main/Script_AE/generate_dataset.py) file is inconsistent with the explanation of the dataset. 
The description I found is [here](https://big-ann-benchmarks.com/neurips21.html):
```
All datasets are in the common binary format that starts with 8 bytes of data consisting of num_points(uint32_t) num_dimensions(uint32)...
```

So, in order to parse this dataset, I think you should read a 8-byte buffer first (num_vector and num_dim).

However, in your codes, you read a 4-byte value in every loop? 
```python
while 1:

            dim_bin = f.read(4)
            assert dim_bin != b''
            dim, = struct.unpack('i', dim_bin)

            # The next 4 * dim byte is for a vector
            vec = f.read(dim)
            
            # Store it
            vecs += vec
            i += 1
            if i == args.topk:
                break
```

In case you generate a dataset of your own, I download the dataset from the source you provide(i.e., [base.1B.u8bin](https://dl.fbaipublicfiles.com/billion-scale-ann-benchmarks/bigann/base.1B.u8bin)), and the output of python script is:

```bash
vec = f.read(dim)
ValueError: read length must be non-negative or -1
```

Hope you notice this issue soon.

**Comment by Yuming-Xu** [comment]
Thank you for your attentive testing, we did make a mistake here, we uploaded a script that converts from .xvec file to .bin, while it should actually be a script that converts from .bin to .bin.

The current version has been changed, you can try it again. 

Thank you very much for your feedback! 

Note: this repo is for artifact evaluation, We are in the process of open-sourcing SPFresh, which will then be placed in the Microsoft/SPTAG repo:)

**Comment by Sparrow612** [comment]
I think the problem is solved, thank you!
