### ISSUE TITLE
what is refine?

### ISSUE THREAD

**Issue by Funlxy** [SPFresh/SPFresh#12]
A small question, what is done during the refine index and refine graph process? When do I need to refine?

**Comment by Yuming-Xu** [comment]
hello，in my opinion (actually I am not the one who write the original refine code), the refine index is close to a rebuild process, from the BKT and KDT we can see that the refineIndex will rebuild the data structure & remove the deleted data in the index permanently. You can trigger it once you have updated the BKT and KDT with a large amount of data.
The refine graph is a update progress during inserting a vector into graph index, it will update the neighbor of the inserted vectors and the neighbors of the inserted vector's neighbor vector. You need to trigger it once you want to add a vector into graph.
In our modified SPFresh code, refine index is to rebuild the SPANN index based on current index, in detail, it will pre-split some of the postings which are over the given length limit. The reason we write this is that we found that the originally built SPANN index is not balance enough, but it is not included in our final SPFresh evaluation:)

**Comment by Funlxy** [comment]
> hello，in my opinion (actually I am not the one who write the original refine code), the refine index is close to a rebuild process, from the BKT and KDT we can see that the refineIndex will rebuild the data structure & remove the deleted data in the index permanently. You can trigger it once you have updated the BKT and KDT with a large amount of data. The refine graph is a update progress during inserting a vector into graph index, it will update the neighbor of the inserted vectors and the neighbors of the inserted vector's neighbor vector. You need to trigger it once you want to add a vector into graph. In our modified SPFresh code, refine index is to rebuild the SPANN index based on current index, in detail, it will pre-split some of the postings which are over the given length limit. The reason we write this is that we found that the originally built SPANN index is not balance enough, but it is not included in our final SPFresh evaluation:)

Thank you! My problem is solved.
