### ISSUE TITLE
Failt to merge key:xxxx value:xxx since value too long!

### ISSUE THREAD

**Issue by Funlxy** [SPFresh/SPFresh#3]
Hi, When I try to reproduce the experiments in the SPFresh paper, I use Figure9 and Figure10 in the repository for the experiments.
**In Figure9**, the experiment on **In-place Update + Split/Reassign** terminates with the following error.
[4] Failt to merge key:145136 value:24605 since value too long!
[4] Origin Size: 24472, merge size: 133
[4] Merge failed! Posting Size:184, limit: 92
![image](https://github.com/SPFresh/SPFresh/assets/72953830/cfbcf320-2a45-4cdd-a2d9-34a8b537b45b)
The programme then terminates.

Again the same error occurs
**In Figure10, top0, top8, top64, and top128** also show the following error in the log.
[4] Failt to merge key:145733 value:24605 since value too long!
[4] Origin Size: 24472, merge size: 133
[4] Merge failed! Posting Size:184, limit: 92
![image](https://github.com/SPFresh/SPFresh/assets/72953830/e909b4ef-c0d9-45bb-badc-2290928db733)

I found the error should appear in the following code segment.
<img width="1030" alt="90ac32891cfd34562d5f2ad03fcc8a5" src="https://github.com/SPFresh/SPFresh/assets/72953830/4e391e48-f019-4ba0-80af-98814b553402">

I would like to know what to do about this error? The dataset and indexes used are generated by the script you provided in the repository.

Another additional question is that the Recall is very low in my experiments, and the dataset used should be fine, so I would also like to ask you about the possible causes of this problem。

**Comment by Funlxy** [comment]
I solved the above error **by changing the configuration parameter in the file indexloader.ini**:.
PostingPageLimit=3 -> PostingPageLimit=10
SearchPostingPageLimit=4 -> PostingPageLimit=11

But again, a new query arises - are the parameters of the configuration file in the repository the ones used for the experiments in your paper?

**Comment by Funlxy** [comment]
> Hello, these parameters are the ones used in our evaluation. This problem is caused by exceeding the limit length of one posting in block controller, since currently our block controller is designed with static block length assignment (every posting have postingpagelimit + bufferlength + 1 blocks limit), during the update, if the background split/reassign is slower than the foreground insert (you can see your log that the split/reassign jobs are stacked: remain split jobs: 133135) Do you use the [Standard_L16s_v3](https://learn.microsoft.com/en-us/azure/virtual-machines/lsv3-series) instances on Azure? the NVMe SSD disk provided by lsv3 is quite fast(10us R/W with stable tail latency), so if you use a slower storage I suggest to reduce insert thread or add more split thread or raise postingpagelimit(it is the split threshold and can reduce the generated split jobs) :)

Thank you very much for your answer, I am indeed not using Standard_L16s_v3 instances on Azure (ToT).

One issue is that I am getting **low recall of results**, both before and after modifying the parameters(modifying the parameters you mentioned shouldn't have a big impact on the experimental results?).

For Example,the experiment about Data Distribution Shifting:
this is my result：
![image](https://github.com/SPFresh/SPFresh/assets/72953830/4690f23b-497d-4717-8844-1e5674ad971b)
And the results in the paper are as follows：
![image](https://github.com/SPFresh/SPFresh/assets/72953830/bac3f4f1-4408-4064-a176-c89fa00954ed)
Similarly, I have experimented with the sift_2m dataset in Experiment 1 (Motivation), and also got a recall of **only about 0.75** for the static index.

In my understanding, the recall should should only be related to the index building algorithm? (Would it be affected by the server environment used or the read/write speed of the Nvme SSD?)

**Comment by Yuming-Xu** [comment]
> > Hello, these parameters are the ones used in our evaluation. This problem is caused by exceeding the limit length of one posting in block controller, since currently our block controller is designed with static block length assignment (every posting have postingpagelimit + bufferlength + 1 blocks limit), during the update, if the background split/reassign is slower than the foreground insert (you can see your log that the split/reassign jobs are stacked: remain split jobs: 133135) Do you use the [Standard_L16s_v3](https://learn.microsoft.com/en-us/azure/virtual-machines/lsv3-series) instances on Azure? the NVMe SSD disk provided by lsv3 is quite fast(10us R/W with stable tail latency), so if you use a slower storage I suggest to reduce insert thread or add more split thread or raise postingpagelimit(it is the split threshold and can reduce the generated split jobs) :)
> 
> Thank you very much for your answer, I am indeed not using Standard_L16s_v3 instances on Azure (ToT).
> 
> One issue is that I am getting **low recall of results**, both before and after modifying the parameters(modifying the parameters you mentioned shouldn't have a big impact on the experimental results?).
> 
> For Example,the experiment about Data Distribution Shifting: this is my result： ![image](https://private-user-images.githubusercontent.com/72953830/286515155-4690f23b-497d-4717-8844-1e5674ad971b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDUxNjYsIm5iZiI6MTcwMTI0NDg2NiwicGF0aCI6Ii83Mjk1MzgzMC8yODY1MTUxNTUtNDY5MGYyM2ItNDk3ZC00NzE3LTg4NDQtMWU1Njc0YWQ5NzFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA4MDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlYzVkYjljMzQzZjNmMDY4NGM3Mzg4MTUxYzg3MTU1NzY5YjAxYzNiNTJhMjc1OTNjY2FhYjA0ODAwMjc3MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ME_THTY3vWMfEaNlYn7AXYRENfqDoQoXcJESh0LYpqY) And the results in the paper are as follows： ![image](https://private-user-images.githubusercontent.com/72953830/286516248-bac3f4f1-4408-4064-a176-c89fa00954ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDUxNjYsIm5iZiI6MTcwMTI0NDg2NiwicGF0aCI6Ii83Mjk1MzgzMC8yODY1MTYyNDgtYmFjM2Y0ZjEtNDQwOC00MDY0LWExNzYtYzg5ZmEwMDk1NGVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA4MDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMTU1Nzg5NTFiZmExMjdkM2Q1ZDkwMGNkMGM5ZTRiMjRmZmE1OTBjYjc4NDQ1MWIxY2RkZjBhNTViMGYzYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MQW0eWnpEtYkZEjepU1PJc8V7mdgEhXMsJHMPSP1BrI) Similarly, I have experimented with the sift_2m dataset in Experiment 1 (Motivation), and also got a recall of **only about 0.75** for the static index.
> 
> In my understanding, the recall should should only be related to the index building algorithm? (Would it be affected by the server environment used or the read/write speed of the Nvme SSD?)

The low recall of results problem of the curves except static may caused by the latency limit.
You can see in the configuration file that the limit is set to 9.0, and considering that you get a slower disk, you can raise this parameter to avoid the search progress is being cut heavily . (Recall and latency is a trade-off, the more you search ,the higher accuracy you get). 
For the static_2m result, currently I have no idea, either. :(

**Comment by Funlxy** [comment]
> > > Hello, these parameters are the ones used in our evaluation. This problem is caused by exceeding the limit length of one posting in block controller, since currently our block controller is designed with static block length assignment (every posting have postingpagelimit + bufferlength + 1 blocks limit), during the update, if the background split/reassign is slower than the foreground insert (you can see your log that the split/reassign jobs are stacked: remain split jobs: 133135) Do you use the [Standard_L16s_v3](https://learn.microsoft.com/en-us/azure/virtual-machines/lsv3-series) instances on Azure? the NVMe SSD disk provided by lsv3 is quite fast(10us R/W with stable tail latency), so if you use a slower storage I suggest to reduce insert thread or add more split thread or raise postingpagelimit(it is the split threshold and can reduce the generated split jobs) :)
> > 
> > 
> > Thank you very much for your answer, I am indeed not using Standard_L16s_v3 instances on Azure (ToT).
> > One issue is that I am getting **low recall of results**, both before and after modifying the parameters(modifying the parameters you mentioned shouldn't have a big impact on the experimental results?).
> > For Example,the experiment about Data Distribution Shifting: this is my result： ![image](https://private-user-images.githubusercontent.com/72953830/286515155-4690f23b-497d-4717-8844-1e5674ad971b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDUxNjYsIm5iZiI6MTcwMTI0NDg2NiwicGF0aCI6Ii83Mjk1MzgzMC8yODY1MTUxNTUtNDY5MGYyM2ItNDk3ZC00NzE3LTg4NDQtMWU1Njc0YWQ5NzFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA4MDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlYzVkYjljMzQzZjNmMDY4NGM3Mzg4MTUxYzg3MTU1NzY5YjAxYzNiNTJhMjc1OTNjY2FhYjA0ODAwMjc3MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ME_THTY3vWMfEaNlYn7AXYRENfqDoQoXcJESh0LYpqY) And the results in the paper are as follows： ![image](https://private-user-images.githubusercontent.com/72953830/286516248-bac3f4f1-4408-4064-a176-c89fa00954ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDUxNjYsIm5iZiI6MTcwMTI0NDg2NiwicGF0aCI6Ii83Mjk1MzgzMC8yODY1MTYyNDgtYmFjM2Y0ZjEtNDQwOC00MDY0LWExNzYtYzg5ZmEwMDk1NGVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA4MDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMTU1Nzg5NTFiZmExMjdkM2Q1ZDkwMGNkMGM5ZTRiMjRmZmE1OTBjYjc4NDQ1MWIxY2RkZjBhNTViMGYzYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MQW0eWnpEtYkZEjepU1PJc8V7mdgEhXMsJHMPSP1BrI) Similarly, I have experimented with the sift_2m dataset in Experiment 1 (Motivation), and also got a recall of **only about 0.75** for the static index.
> > In my understanding, the recall should should only be related to the index building algorithm? (Would it be affected by the server environment used or the read/write speed of the Nvme SSD?)
> 
> The low recall of results problem of the curves except static may caused by the latency limit. You can see in the configuration file that the limit is set to 9.0, and considering that you get a slower disk, you can raise this parameter to avoid the search progress is being cut heavily . (Recall and latency is a trade-off, the more you search ,the higher accuracy you get). For the static_2m result, currently I have no idea, either. :(

Thank you! I'll try a few more times. Maybe the best solution is to use L16s v3.

**Comment by Funlxy** [comment]
> > > Hello, these parameters are the ones used in our evaluation. This problem is caused by exceeding the limit length of one posting in block controller, since currently our block controller is designed with static block length assignment (every posting have postingpagelimit + bufferlength + 1 blocks limit), during the update, if the background split/reassign is slower than the foreground insert (you can see your log that the split/reassign jobs are stacked: remain split jobs: 133135) Do you use the [Standard_L16s_v3](https://learn.microsoft.com/en-us/azure/virtual-machines/lsv3-series) instances on Azure? the NVMe SSD disk provided by lsv3 is quite fast(10us R/W with stable tail latency), so if you use a slower storage I suggest to reduce insert thread or add more split thread or raise postingpagelimit(it is the split threshold and can reduce the generated split jobs) :)
> > 
> > 
> > Thank you very much for your answer, I am indeed not using Standard_L16s_v3 instances on Azure (ToT).
> > One issue is that I am getting **low recall of results**, both before and after modifying the parameters(modifying the parameters you mentioned shouldn't have a big impact on the experimental results?).
> > For Example,the experiment about Data Distribution Shifting: this is my result： ![image](https://private-user-images.githubusercontent.com/72953830/286515155-4690f23b-497d-4717-8844-1e5674ad971b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDUxNjYsIm5iZiI6MTcwMTI0NDg2NiwicGF0aCI6Ii83Mjk1MzgzMC8yODY1MTUxNTUtNDY5MGYyM2ItNDk3ZC00NzE3LTg4NDQtMWU1Njc0YWQ5NzFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA4MDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlYzVkYjljMzQzZjNmMDY4NGM3Mzg4MTUxYzg3MTU1NzY5YjAxYzNiNTJhMjc1OTNjY2FhYjA0ODAwMjc3MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ME_THTY3vWMfEaNlYn7AXYRENfqDoQoXcJESh0LYpqY) And the results in the paper are as follows： ![image](https://private-user-images.githubusercontent.com/72953830/286516248-bac3f4f1-4408-4064-a176-c89fa00954ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDUxNjYsIm5iZiI6MTcwMTI0NDg2NiwicGF0aCI6Ii83Mjk1MzgzMC8yODY1MTYyNDgtYmFjM2Y0ZjEtNDQwOC00MDY0LWExNzYtYzg5ZmEwMDk1NGVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA4MDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMTU1Nzg5NTFiZmExMjdkM2Q1ZDkwMGNkMGM5ZTRiMjRmZmE1OTBjYjc4NDQ1MWIxY2RkZjBhNTViMGYzYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MQW0eWnpEtYkZEjepU1PJc8V7mdgEhXMsJHMPSP1BrI) Similarly, I have experimented with the sift_2m dataset in Experiment 1 (Motivation), and also got a recall of **only about 0.75** for the static index.
> > In my understanding, the recall should should only be related to the index building algorithm? (Would it be affected by the server environment used or the read/write speed of the Nvme SSD?)
> 
> The low recall of results problem of the curves except static may caused by the latency limit. You can see in the configuration file that the limit is set to 9.0, and considering that you get a slower disk, you can raise this parameter to avoid the search progress is being cut heavily . (Recall and latency is a trade-off, the more you search ,the higher accuracy you get). For the static_2m result, currently I have no idea, either. :(

Sorry, there's one more little problem.
I'm looking to replace a 2T NvmeSSD with 800KIOPS, 7000MB/S, which should be about the same rate as the L16s_v3, right?
Should the 2T size be enough for the experiments in the paper?

**Comment by Yuming-Xu** [comment]
> > > > Hello, these parameters are the ones used in our evaluation. This problem is caused by exceeding the limit length of one posting in block controller, since currently our block controller is designed with static block length assignment (every posting have postingpagelimit + bufferlength + 1 blocks limit), during the update, if the background split/reassign is slower than the foreground insert (you can see your log that the split/reassign jobs are stacked: remain split jobs: 133135) Do you use the [Standard_L16s_v3](https://learn.microsoft.com/en-us/azure/virtual-machines/lsv3-series) instances on Azure? the NVMe SSD disk provided by lsv3 is quite fast(10us R/W with stable tail latency), so if you use a slower storage I suggest to reduce insert thread or add more split thread or raise postingpagelimit(it is the split threshold and can reduce the generated split jobs) :)
> > > 
> > > 
> > > Thank you very much for your answer, I am indeed not using Standard_L16s_v3 instances on Azure (ToT).
> > > One issue is that I am getting **low recall of results**, both before and after modifying the parameters(modifying the parameters you mentioned shouldn't have a big impact on the experimental results?).
> > > For Example,the experiment about Data Distribution Shifting: this is my result： ![image](https://private-user-images.githubusercontent.com/72953830/286515155-4690f23b-497d-4717-8844-1e5674ad971b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDUxNjYsIm5iZiI6MTcwMTI0NDg2NiwicGF0aCI6Ii83Mjk1MzgzMC8yODY1MTUxNTUtNDY5MGYyM2ItNDk3ZC00NzE3LTg4NDQtMWU1Njc0YWQ5NzFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA4MDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlYzVkYjljMzQzZjNmMDY4NGM3Mzg4MTUxYzg3MTU1NzY5YjAxYzNiNTJhMjc1OTNjY2FhYjA0ODAwMjc3MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ME_THTY3vWMfEaNlYn7AXYRENfqDoQoXcJESh0LYpqY) And the results in the paper are as follows： ![image](https://private-user-images.githubusercontent.com/72953830/286516248-bac3f4f1-4408-4064-a176-c89fa00954ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDUxNjYsIm5iZiI6MTcwMTI0NDg2NiwicGF0aCI6Ii83Mjk1MzgzMC8yODY1MTYyNDgtYmFjM2Y0ZjEtNDQwOC00MDY0LWExNzYtYzg5ZmEwMDk1NGVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA4MDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMTU1Nzg5NTFiZmExMjdkM2Q1ZDkwMGNkMGM5ZTRiMjRmZmE1OTBjYjc4NDQ1MWIxY2RkZjBhNTViMGYzYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MQW0eWnpEtYkZEjepU1PJc8V7mdgEhXMsJHMPSP1BrI) Similarly, I have experimented with the sift_2m dataset in Experiment 1 (Motivation), and also got a recall of **only about 0.75** for the static index.
> > > In my understanding, the recall should should only be related to the index building algorithm? (Would it be affected by the server environment used or the read/write speed of the Nvme SSD?)
> > 
> > 
> > The low recall of results problem of the curves except static may caused by the latency limit. You can see in the configuration file that the limit is set to 9.0, and considering that you get a slower disk, you can raise this parameter to avoid the search progress is being cut heavily . (Recall and latency is a trade-off, the more you search ,the higher accuracy you get). For the static_2m result, currently I have no idea, either. :(
> 
> Sorry, there's one more little problem. I'm looking to replace a 2T NvmeSSD with 800KIOPS, 7000MB/S, which should be about the same rate as the L16s_v3, right? Should the 2T size be enough for the experiments in the paper?

Sure, it seems your device gets higher throughput and bandwidth (you can access [Standard_L16s_v3](https://learn.microsoft.com/en-us/azure/virtual-machines/lsv3-series) to see the parameter of Lsv3), but I can not sure the R/W latency can be the same to lsv3, if not, you may need to change some parameters in the configuration file. I recommend you to try the experiment for figure 7 and figure out whether it performs better than lsv3
