### ISSUE TITLE
Question about the files of deleteset/reserveset/currentset 

### ISSUE THREAD

**Issue by TyangJN** [SPFresh/SPFresh#7]
In the file `generateOverallPerformanceTraceAndTruth.sh.`
You have defined the following variables:
```
deletesetname="spacev100m_update_set"
reservesetname="spacev100m_update_reserve"
currentsetname="spacev100m_update_current"
```
Then these variables will be utilizied by the functions in usefultool, which should be the name or path of certain files.
Since i didn't find any information about these file, I would like to ask, how to generate these files?

**Comment by Yuming-Xu** [comment]
Hello, in the "generateOverallPerformanceTraceAndTruth.sh."
you can see in the line 8:
/home/sosp/SPFresh/Release/usefultool -GenTrace *******--CurrentListFileName spacev100m_update_current --ReserveListFileName -NewDataSetFileName spacev100m_update_set
This command will generate those files you mentioned, and you can change those parameters to change those files to the path where you want to store those files.
I forget to change the names of the files in the parameters, thank you for your feedback:)

**Comment by Mysshuaige** [comment]
> Hello, in the "generateOverallPerformanceTraceAndTruth.sh." you can see in the line 8: /home/sosp/SPFresh/Release/usefultool -GenTrace *******--CurrentListFileName spacev100m_update_current --ReserveListFileName -NewDataSetFileName spacev100m_update_set This command will generate those files you mentioned, and you can change those parameters to change those files to the path where you want to store those files. I forget to change the names of the files in the parameters, thank you for your feedback:)

您好，我在运行bash generateOverallPerformanceTraceAndTruth.sh的时候遇到了这个错误，数据集以及路径配置都跟您设置的相同，我不知道为什么会出现这个bug。
![image](https://github.com/SPFresh/SPFresh/assets/137894571/89d93c87-6299-4c0d-abf8-d5e50977fba2)

**Comment by Yuming-Xu** [comment]
> > Hello, in the "generateOverallPerformanceTraceAndTruth.sh." you can see in the line 8: /home/sosp/SPFresh/Release/usefultool -GenTrace *******--CurrentListFileName spacev100m_update_current --ReserveListFileName -NewDataSetFileName spacev100m_update_set This command will generate those files you mentioned, and you can change those parameters to change those files to the path where you want to store those files. I forget to change the names of the files in the parameters, thank you for your feedback:)
> 
> 您好，我在运行bash generateOverallPerformanceTraceAndTruth.sh的时候遇到了这个错误，数据集以及路径配置都跟您设置的相同，我不知道为什么会出现这个bug。 ![image](https://private-user-images.githubusercontent.com/137894571/298535686-89d93c87-6299-4c0d-abf8-d5e50977fba2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTc5MDIsIm5iZiI6MTcwNTkxNzYwMiwicGF0aCI6Ii8xMzc4OTQ1NzEvMjk4NTM1Njg2LTg5ZDkzYzg3LTYyOTktNGMwZC1hYmY4LWQ1ZTUwOTc3ZmJhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQxMDAwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDUyNTNlYWNkYjA1N2ZhMDI4MmY5YmVmMDY3OWM4ZjdhYjBhMzJiMTc0NjQ3Mjc1YzE3YWUxNWE5YWNiYjA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wC3rOpYyXRSarFrk02jSITRGf62EK4DQEJaW6jjwZz4)

你好，从你的结果来看你并没有Load VectorSet，也就是 --VectorPath /home/sosp/data/spacev_data/spacev200m_base.i8bin并不存在:)

**Comment by TyangJN** [comment]
> > > Hello, in the "generateOverallPerformanceTraceAndTruth.sh." you can see in the line 8: /home/sosp/SPFresh/Release/usefultool -GenTrace *******--CurrentListFileName spacev100m_update_current --ReserveListFileName -NewDataSetFileName spacev100m_update_set This command will generate those files you mentioned, and you can change those parameters to change those files to the path where you want to store those files. I forget to change the names of the files in the parameters, thank you for your feedback:)
> > 
> > 
> > 您好，我在运行bash generateOverallPerformanceTraceAndTruth.sh的时候遇到了这个错误，数据集以及路径配置都跟您设置的相同，我不知道为什么会出现这个bug。 ![image](https://private-user-images.githubusercontent.com/137894571/298535686-89d93c87-6299-4c0d-abf8-d5e50977fba2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTc5MDIsIm5iZiI6MTcwNTkxNzYwMiwicGF0aCI6Ii8xMzc4OTQ1NzEvMjk4NTM1Njg2LTg5ZDkzYzg3LTYyOTktNGMwZC1hYmY4LWQ1ZTUwOTc3ZmJhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQxMDAwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDUyNTNlYWNkYjA1N2ZhMDI4MmY5YmVmMDY3OWM4ZjdhYjBhMzJiMTc0NjQ3Mjc1YzE3YWUxNWE5YWNiYjA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wC3rOpYyXRSarFrk02jSITRGf62EK4DQEJaW6jjwZz4)
> 
> 你好，从你的结果来看你并没有Load VectorSet，也就是 --VectorPath /home/sosp/data/spacev_data/spacev200m_base.i8bin并不存在:)

谢谢你的耐心回复，有一个小的优化点针对generate_dataset.py，可以使用np.memmap()函数快速生成文件，代码如下：
```
import numpy as np
import os
import struct

def xbin_mmap(fname, dtype, output_filename, maxn=-1):
    """ mmap the competition file format for a given type of items """
    n, d = map(int, np.fromfile(fname, dtype="uint32", count=2))

    assert os.stat(fname).st_size == 8 + n * d * np.dtype(dtype).itemsize
    if maxn > 0:
        n = min(n, maxn)
    memmap_data = np.memmap(fname, dtype=dtype, mode="r", offset=8, shape=(n, d))
    if memmap_data.dtype != np.int8:
        memmap_data = memmap_data.astype(np.uint8)
    # write data
    with open(output_filename, 'wb') as file:
        file.write(struct.pack('i', n))
        file.write(struct.pack('i', d))
        file.write(memmap_data.tobytes())
        
xbin_mmap("spacev1b_base.i8bin", dtype='int8', maxn=100000000, output_filename='spacev100m_base.i8bin')

```
