### ISSUE TITLE
which parameters should i used if i want to use rocksdb mode

### ISSUE THREAD

**Issue by jonathanJia1** [SPFresh/SPFresh#8]
hi

i am trying to run spfresh with rocksdb mode with "UseKV=true". But i am not clear about the parameters sets i need to use.
would you please advise?

**Comment by Yuming-Xu** [comment]
Hello, please refer to the issue #5 for the parameters setting

Note that Our SPDK-based BlockController has a very different performance in terms of read & write (especially in write) compared to RocksDB, the AppendThreadNum should be set much higher than InsertThreadNum to make sure the background split&merge&reassign can catch up with the foreground insertion:)

**Comment by jonathanJia1** [comment]
Thanks for your reply. 
Now i can run RocksDB on 1m dataset. but the code failed when i tried 100m datassets. 
Would you please advise any debug idea?

Error in Put: While open a file for random read: index/output_100m_u8/kv_data/006834.blob: Too many open files, key: 9297970
[4] Error in Put: While open a file for random read: index/output_100m_u8/kv_data/006834.blob: Too many open files, key: 9297979
[4] Error in Put: While open a file for random read: index/output_100m_u8/kv_data/006834.blob: Too many open files, key: 9297980

**Comment by Yuming-Xu** [comment]
Hello, you need to grow the maximum number of open file descriptors of your machine since RocksDB need to open all the blob/sst files, please google "ulimit" command to find out how to change the number:)

**Comment by jonathanJia1** [comment]
Let me try.
Thanks so much.

**Comment by jonathanJia1** [comment]
Thanks. It works.
Please close this issue.
